// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 07/11/2025, 12.29.32
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["D:/Projects/devfolio/blog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/devfolio/blog/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/devfolio/blog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/devfolio/blog/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/devfolio/blog/plugins/**/*.{js,ts,mjs}","D:/Projects/devfolio/blog/composables/**/*.{js,ts,mjs}","D:/Projects/devfolio/blog/utils/**/*.{js,ts,mjs}","D:/Projects/devfolio/blog/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/devfolio/blog/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/devfolio/blog/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/devfolio/blog/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["16"] = "D:/Projects/devfolio/blog/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;